// Code generated by Slice Machine. DO NOT EDIT.
import Cards from "./Cards"
import ContactForm from "./ContactForm"
import CtaSection from "./CtaSection"
import Hero from "./Hero"
import RichText from "./RichText"

export const components = {
  cards: Cards,
  contact_form: ContactForm,
  cta_section: CtaSection,
  hero: Hero,
  rich_text: RichText,
}
